name: Build UEFI for release
on:
  push:
    tags:
      - "*"
env:
  CI_BUILD: true
permissions:
  contents: write
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build UEFI
        run: bash ./setup_env.sh -p apt && bash ./build_active_devices.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          files: |
            Mu-*
